---
- include_tasks: setup-RedHat.yml

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Create docker service override dir
  when: http_proxy|default('')
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory

- name: Install systemd override
  when: http_proxy|default('')
  copy:
    content: |
      [Service]
      Environment=http_proxy={{http_proxy}}
      Environment=https_proxy={{https_proxy}}
      Environment=no_proxy={{no_proxy}}
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart docker

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
