---
#- name: Ensure old versions of Docker are not installed.
#  package:
#    name:
#      - docker
#      - docker-common
#      - docker-ce
#      - docker-ee
#    state: absent

- name: Configure OracleLinux addons repo.
  when: ansible_distribution == "OracleLinux"
  ini_file:
    dest: '/etc/yum.repos.d/oracle-linux-ol{{ ansible_distribution_major_version }}.repo'
    section: 'ol{{ ansible_distribution_major_version }}_addons'
    option: enabled
    value: '1'
